version: "3"
services:
    php:
        build:
            dockerfile: tests/docker/Dockerfile
            context: .
        volumes:
            - ./tests/tmp/.composer:/root/.composer:rw
            - .:/app
        environment:
            - PHP_IDE_CONFIG='serverName=host.docker.internal'
            - XDEBUG_TRIGGER=1
            - TZ=UTC
            - TIMEZONE=UTC
            - IN_DOCKER=docker
            - PHP_XDEBUG_ENABLED=1
            - XDEBUG_CONFIG="remote_host=host.docker.internal"
            - PHP_IDE_CONFIG="serverName=Docker"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        tty: true
    node:
        image: node:12
        volumes:
            - .:/app
